In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


In [2]:
df = pd.read_csv('C:/Users/moria/Documents/Python Projects/heart.csv')

In [3]:
df['target'] = df['target'].replace(to_replace = [0, 1], value = [True, False])
df.drop([92, 158, 163, 164, 251], inplace = True)
df.drop(85, inplace = True)

In [4]:
X = df.drop(columns=['target'])
y = df.target
r_state = 29

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=r_state) 

In [6]:
model_1 = LogisticRegression(random_state=r_state)
model_1.fit(X_train, y_train)

C:\Users\moria\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=29, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
model_1_pred = model_1.predict(X_test)

In [8]:
model_1_pred

array([ True, False, False,  True,  True, False,  True, False, False,
        True, False,  True, False, False,  True,  True, False, False,
       False, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False,  True, False, False, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False, False, False,  True, False, False, False, False])

In [9]:
y_test.to_numpy()

array([ True, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True, False, False,  True, False, False,  True, False,
        True, False, False, False, False,  True, False,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False])

In [10]:
model_1.score(X_test, y_test)

0.8585858585858586

In [11]:
df_one_hot = pd.get_dummies(df, columns = ['ca', 'cp', 'sex', 'exang', 'thal', 'restecg', 'slope'])
df_one_hot.head()

age  trestbps  chol  fbs  thalach  oldpeak  target  ca_0  ca_1  ca_2  ...  \
0   63       145   233    1      150      2.3   False     1     0     0  ...   
1   37       130   250    0      187      3.5   False     1     0     0  ...   
2   41       130   204    0      172      1.4   False     1     0     0  ...   
3   56       120   236    0      178      0.8   False     1     0     0  ...   
4   57       120   354    0      163      0.6   False     1     0     0  ...   

   thal_0  thal_1  thal_2  thal_3  restecg_0  restecg_1  restecg_2  slope_0  \
0       0       1       0       0          1          0          0        1   
1       0       0       1       0          0          1          0        1   
2       0       0       1       0          1          0          0        0   
3       0       0       1       0          0          1          0        0   
4       0       0       1       0          0          1          0        0   

   slope_1  slope_2  
0        0        0  
1        0        0  
2        0        1  
3        0        1  
4        0        1  

[5 rows x 29 columns]

In [23]:
columns = ['age', 'sex_0','sex_1', 'ca_1', 'ca_2', 'ca_3', 'cp_0', 'exang_1', 'oldpeak', 'thalach', 'trestbps', 'restecg_0', 'restecg_1', 'restecg_2', 'fbs']
subset = df_one_hot[columns]
subset.head()
subset.describe()

age       sex_0       sex_1        ca_1        ca_2        ca_3  \
count  297.000000  297.000000  297.000000  297.000000  297.000000  297.000000   
mean    54.468013    0.319865    0.680135    0.218855    0.127946    0.067340   
std      9.016491    0.467211    0.467211    0.414168    0.334594    0.251033   
min     29.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%     48.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%     56.000000    0.000000    1.000000    0.000000    0.000000    0.000000   
75%     61.000000    1.000000    1.000000    0.000000    0.000000    0.000000   
max     77.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             cp_0     exang_1     oldpeak     thalach    trestbps   restecg_0  \
count  297.000000  297.000000  297.000000  297.000000  297.000000  297.000000   
mean     0.478114    0.329966    1.053535  149.430976  131.636364    0.488215   
std      0.500364    0.470994    1.165696   23.014452   17.672769    0.500705   
min      0.000000    0.000000    0.000000   71.000000   94.000000    0.000000   
25%      0.000000    0.000000    0.000000  133.000000  120.000000    0.000000   
50%      0.000000    0.000000    0.800000  152.000000  130.000000    0.000000   
75%      1.000000    1.000000    1.600000  166.000000  140.000000    1.000000   
max      1.000000    1.000000    6.200000  202.000000  200.000000    1.000000   

        restecg_1   restecg_2         fbs  
count  297.000000  297.000000  297.000000  
mean     0.498316    0.013468    0.148148  
std      0.500841    0.115462    0.355846  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      1.000000    0.000000    0.000000  
max      1.000000    1.000000    1.000000

In [13]:
X = subset
y = df_one_hot.target
r_state = 30

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = r_state)

In [15]:
model_2 = LogisticRegression(random_state = r_state)
model_2.fit(X_train, y_train)

C:\Users\moria\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=30, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
model_2_pred = model_2.predict(X_test)

In [17]:
model_2_pred

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False,  True,  True, False,  True, False, False,
       False, False,  True,  True, False,  True, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False,  True, False,  True, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False,  True, False, False, False,  True,  True, False,  True,
        True, False,  True, False,  True, False, False, False, False])

In [18]:
y_test.to_numpy()

array([ True,  True,  True, False, False,  True,  True, False, False,
       False, False, False,  True,  True, False,  True,  True, False,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
        True,  True, False,  True, False,  True, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True, False,
       False,  True, False, False, False,  True,  True, False,  True,
       False, False,  True, False,  True, False, False, False,  True])

In [19]:
model_2.score(X_test, y_test)

0.8787878787878788

In [29]:
normalized_X = preprocessing.scale(X)

In [30]:
X = normalized_X
y = df_one_hot.target

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = r_state)

In [32]:
model_3 = LogisticRegression(random_state = r_state)
model_3.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=30, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
model_3_pred = model_3.predict(X_test)

In [34]:
model_3_pred

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False,  True,  True, False,  True, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False,  True, False, False, False,  True,  True, False,  True,
        True, False,  True, False,  True, False, False, False, False])

In [36]:
y_test.to_numpy()

array([ True,  True,  True, False, False,  True,  True, False, False,
       False, False, False,  True,  True, False,  True,  True, False,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
        True,  True, False,  True, False,  True, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True, False,
       False,  True, False, False, False,  True,  True, False,  True,
       False, False,  True, False,  True, False, False, False,  True])

In [37]:
model_3.score(X_test, y_test)

0.8585858585858586