In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


In [2]:
df = pd.read_csv('C:/Users/moria/Documents/Python Projects/heart.csv')

In [3]:
df['target'] = df['target'].replace(to_replace = [0, 1], value = [True, False])
df.drop([92, 158, 163, 164, 251], inplace = True)
df.drop(85, inplace = True)

For my first model I just used the data with the changes I made to it during the EDA portion. 

In [4]:
X = df.drop(columns=['target'])
y = df.target
r_state = 29

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=r_state) 

In [6]:
model_1 = LogisticRegression(random_state=r_state)
model_1.fit(X_train, y_train)

C:\Users\moria\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=29, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
model_1_pred = model_1.predict(X_test)

In [8]:
model_1_pred

array([ True, False, False,  True,  True, False,  True, False, False,
        True, False,  True, False, False,  True,  True, False, False,
       False, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False,  True, False, False, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False, False, False,  True, False, False, False, False])

In [9]:
y_test.to_numpy()

array([ True, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True, False, False,  True, False, False,  True, False,
        True, False, False, False, False,  True, False,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False])

In [10]:
model_1.score(X_test, y_test)

0.8585858585858586

The accuracy is about 86%, but I wonder whether tweaking the data a little more could make the model more accurate. For the second model I converted columns with categorical data to one-hot and selected the columns that seemed to correlate best with the target.

In [62]:
columns = ['sex', 'cp', 'thalach', 'exang', 'oldpeak', 'ca', 'slope', 'thal']
subset = df[columns]
subset.head()

sex  cp  thalach  exang  oldpeak  ca  slope  thal
0    1   3      150      0      2.3   0      0     1
1    1   2      187      0      3.5   0      0     2
2    0   1      172      0      1.4   0      2     2
3    1   1      178      0      0.8   0      2     2
4    0   0      163      1      0.6   0      2     2

In [64]:
subset = pd.get_dummies(subset, columns =  ['sex', 'cp', 'exang', 'ca', 'slope', 'thal'])


In [65]:
X = subset
y = df.target


In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = r_state)

In [67]:
model_2 = LogisticRegression(random_state = r_state)
model_2.fit(X_train, y_train)

C:\Users\moria\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=29, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [68]:
model_2_pred = model_2.predict(X_test)

In [69]:
model_2_pred

array([ True, False, False,  True,  True, False,  True, False, False,
        True, False,  True, False, False,  True,  True, False, False,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False, False, False, False, False, False, False, False])

In [70]:
y_test.to_numpy()

array([ True, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True, False, False,  True, False, False,  True, False,
        True, False, False, False, False,  True, False,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False])

In [71]:
model_2.score(X_test, y_test)

0.8686868686868687

The changes I made resulted in a more accurate second model! 